[general]
iata = "RTM"

[serial]
#ports = ["/dev/ttyACM0"]
ports = ["/dev/serial/by-id/usb-RAKwireless_WisCore_RAK4631_Board_619E6DDF4F95D2BC-if00"]
#ports = ["/dev/ttyMC_RP_RAK"]

[remote_serial]
enabled = true
allowed_companions = [public key companion1,public key companion2]

[[broker]]
name = "my-mqtt"
enabled = true
server = "mqtt.example.com"
port = 1883

[broker.auth]
method = "password"
username = "my_username"
password = "my_password"
